# Name of the workflow
name: Super-Linter

# Trigger
on: push

# Jobs to run on trigger
jobs:
  # Job name
  super-lint:
    name: Lint code base
    # A Runner is the container enviroment that will run the code
    # Default containers are: Ubuntu, Windows, and macOS
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
